name: rock
channels:
  - conda-forge
  - defaults
dependencies:
  - cookiecutter=1.6
# --- C++ dependencies ---
# - catch2=2.6
  - cmake=3.13
  - conan=1.12
  - ninja=1.9
  - scikit-build=0.8
  - bump2version=5.8
  - python=3.6
# --- dev dependencies ---
  - pybind11=2.2
  - swig=3.0
# C++ project dependencies
  - eigen 3.3
# --- python build requirements ---
  - flake8=3.7
  - coverage=4.5
